// Especialidades médicas reconhecidas pelo CFM (Conselho Federal de Medicina)
export const ESPECIALIDADES_MEDICAS = [
  { value: 'Acupuntura', label: 'Acupuntura' },
  { value: 'Alergia e Imunologia', label: 'Alergia e Imunologia' },
  { value: 'Anestesiologia', label: 'Anestesiologia' },
  { value: 'Angiologia', label: 'Angiologia' },
  { value: 'Cancerologia', label: 'Cancerologia' },
  { value: 'Cardiologia', label: 'Cardiologia' },
  { value: 'Cirurgia Cardiovascular', label: 'Cirurgia Cardiovascular' },
  { value: 'Cirurgia da Mão', label: 'Cirurgia da Mão' },
  { value: 'Cirurgia de Cabeça e Pescoço', label: 'Cirurgia de Cabeça e Pescoço' },
  { value: 'Cirurgia do Aparelho Digestivo', label: 'Cirurgia do Aparelho Digestivo' },
  { value: 'Cirurgia Geral', label: 'Cirurgia Geral' },
  { value: 'Cirurgia Pediátrica', label: 'Cirurgia Pediátrica' },
  { value: 'Cirurgia Plástica', label: 'Cirurgia Plástica' },
  { value: 'Cirurgia Torácica', label: 'Cirurgia Torácica' },
  { value: 'Cirurgia Vascular', label: 'Cirurgia Vascular' },
  { value: 'Clínica Médica', label: 'Clínica Médica' },
  { value: 'Coloproctologia', label: 'Coloproctologia' },
  { value: 'Dermatologia', label: 'Dermatologia' },
  { value: 'Endocrinologia e Metabologia', label: 'Endocrinologia e Metabologia' },
  { value: 'Endoscopia', label: 'Endoscopia' },
  { value: 'Gastroenterologia', label: 'Gastroenterologia' },
  { value: 'Genética Médica', label: 'Genética Médica' },
  { value: 'Geriatria', label: 'Geriatria' },
  { value: 'Ginecologia e Obstetrícia', label: 'Ginecologia e Obstetrícia' },
  { value: 'Hematologia e Hemoterapia', label: 'Hematologia e Hemoterapia' },
  { value: 'Homeopatia', label: 'Homeopatia' },
  { value: 'Infectologia', label: 'Infectologia' },
  { value: 'Mastologia', label: 'Mastologia' },
  { value: 'Medicina de Emergência', label: 'Medicina de Emergência' },
  { value: 'Medicina de Família e Comunidade', label: 'Medicina de Família e Comunidade' },
  { value: 'Medicina do Trabalho', label: 'Medicina do Trabalho' },
  { value: 'Medicina do Tráfego', label: 'Medicina do Tráfego' },
  { value: 'Medicina Esportiva', label: 'Medicina Esportiva' },
  { value: 'Medicina Física e Reabilitação', label: 'Medicina Física e Reabilitação' },
  { value: 'Medicina Intensiva', label: 'Medicina Intensiva' },
  { value: 'Medicina Legal e Perícia Médica', label: 'Medicina Legal e Perícia Médica' },
  { value: 'Medicina Nuclear', label: 'Medicina Nuclear' },
  { value: 'Medicina Preventiva e Social', label: 'Medicina Preventiva e Social' },
  { value: 'Nefrologia', label: 'Nefrologia' },
  { value: 'Neurocirurgia', label: 'Neurocirurgia' },
  { value: 'Neurologia', label: 'Neurologia' },
  { value: 'Nutrologia', label: 'Nutrologia' },
  { value: 'Oftalmologia', label: 'Oftalmologia' },
  { value: 'Oncologia Clínica', label: 'Oncologia Clínica' },
  { value: 'Ortopedia e Traumatologia', label: 'Ortopedia e Traumatologia' },
  { value: 'Otorrinolaringologia', label: 'Otorrinolaringologia' },
  { value: 'Patologia', label: 'Patologia' },
  { value: 'Patologia Clínica / Medicina Laboratorial', label: 'Patologia Clínica / Medicina Laboratorial' },
  { value: 'Pediatria', label: 'Pediatria' },
  { value: 'Pneumologia', label: 'Pneumologia' },
  { value: 'Psiquiatria', label: 'Psiquiatria' },
  { value: 'Radiologia e Diagnóstico por Imagem', label: 'Radiologia e Diagnóstico por Imagem' },
  { value: 'Reumatologia', label: 'Reumatologia' },
  { value: 'Urologia', label: 'Urologia' },
];
